# Generated by Django 5.1.4 on 2024-12-19 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='user',
        ),
        migrations.AddField(
            model_name='file',
            name='user_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
